// proto/gen/fx/v1/fx.proto
// proto/gen/fx/v1/fx.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: fx/v1/fx.proto

package fxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency  string                 `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency string                 `protobuf:"bytes,2,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_fx_v1_fx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_proto_rawDescGZIP(), []int{0}
}

func (x *Rate) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *Rate) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *Rate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type UpdateRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*Rate                `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRatesRequest) Reset() {
	*x = UpdateRatesRequest{}
	mi := &file_fx_v1_fx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatesRequest) ProtoMessage() {}

func (x *UpdateRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRatesRequest) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRatesRequest) GetRates() []*Rate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type UpdateRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRatesResponse) Reset() {
	*x = UpdateRatesResponse{}
	mi := &file_fx_v1_fx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRatesResponse) ProtoMessage() {}

func (x *UpdateRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRatesResponse.ProtoReflect.Descriptor instead.
func (*UpdateRatesResponse) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sederhana sesuai handler: string + double
type ConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"` // "USD"
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`       // "IDR"
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`                               // 123.45
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_fx_v1_fx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_proto_rawDescGZIP(), []int{3}
}

func (x *ConvertRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ConvertRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"` // hasil konversi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_fx_v1_fx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_proto_rawDescGZIP(), []int{4}
}

func (x *ConvertResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_fx_v1_fx_proto protoreflect.FileDescriptor

const file_fx_v1_fx_proto_rawDesc = "" +
	"\n" +
	"\x0efx/v1/fx.proto\x12\x05fx.v1\"f\n" +
	"\x04Rate\x12#\n" +
	"\rbase_currency\x18\x01 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x02 \x01(\tR\rquoteCurrency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\"7\n" +
	"\x12UpdateRatesRequest\x12!\n" +
	"\x05rates\x18\x01 \x03(\v2\v.fx.v1.RateR\x05rates\"I\n" +
	"\x13UpdateRatesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x0eConvertRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\")\n" +
	"\x0fConvertResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount2\x8b\x01\n" +
	"\tFxService\x12D\n" +
	"\vUpdateRates\x12\x19.fx.v1.UpdateRatesRequest\x1a\x1a.fx.v1.UpdateRatesResponse\x128\n" +
	"\aConvert\x12\x15.fx.v1.ConvertRequest\x1a\x16.fx.v1.ConvertResponseB=Z;github.com/example/payment-gateway-poc/proto/gen/fx/v1;fxv1b\x06proto3"

var (
	file_fx_v1_fx_proto_rawDescOnce sync.Once
	file_fx_v1_fx_proto_rawDescData []byte
)

func file_fx_v1_fx_proto_rawDescGZIP() []byte {
	file_fx_v1_fx_proto_rawDescOnce.Do(func() {
		file_fx_v1_fx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fx_v1_fx_proto_rawDesc), len(file_fx_v1_fx_proto_rawDesc)))
	})
	return file_fx_v1_fx_proto_rawDescData
}

var file_fx_v1_fx_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fx_v1_fx_proto_goTypes = []any{
	(*Rate)(nil),                // 0: fx.v1.Rate
	(*UpdateRatesRequest)(nil),  // 1: fx.v1.UpdateRatesRequest
	(*UpdateRatesResponse)(nil), // 2: fx.v1.UpdateRatesResponse
	(*ConvertRequest)(nil),      // 3: fx.v1.ConvertRequest
	(*ConvertResponse)(nil),     // 4: fx.v1.ConvertResponse
}
var file_fx_v1_fx_proto_depIdxs = []int32{
	0, // 0: fx.v1.UpdateRatesRequest.rates:type_name -> fx.v1.Rate
	1, // 1: fx.v1.FxService.UpdateRates:input_type -> fx.v1.UpdateRatesRequest
	3, // 2: fx.v1.FxService.Convert:input_type -> fx.v1.ConvertRequest
	2, // 3: fx.v1.FxService.UpdateRates:output_type -> fx.v1.UpdateRatesResponse
	4, // 4: fx.v1.FxService.Convert:output_type -> fx.v1.ConvertResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fx_v1_fx_proto_init() }
func file_fx_v1_fx_proto_init() {
	if File_fx_v1_fx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_v1_fx_proto_rawDesc), len(file_fx_v1_fx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_v1_fx_proto_goTypes,
		DependencyIndexes: file_fx_v1_fx_proto_depIdxs,
		MessageInfos:      file_fx_v1_fx_proto_msgTypes,
	}.Build()
	File_fx_v1_fx_proto = out.File
	file_fx_v1_fx_proto_goTypes = nil
	file_fx_v1_fx_proto_depIdxs = nil
}
