// proto/gen/fx/v1/fx_admin.proto
// proto/gen/fx/v1/fx_admin.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: fx/v1/fx_admin.proto

package fxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshRandomRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRandomRatesRequest) Reset() {
	*x = RefreshRandomRatesRequest{}
	mi := &file_fx_v1_fx_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRandomRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRandomRatesRequest) ProtoMessage() {}

func (x *RefreshRandomRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRandomRatesRequest.ProtoReflect.Descriptor instead.
func (*RefreshRandomRatesRequest) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_admin_proto_rawDescGZIP(), []int{0}
}

type RefreshRandomRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Pushed        []*Rate                `protobuf:"bytes,3,rep,name=pushed,proto3" json:"pushed,omitempty"` // reuse Rate dari fx.proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRandomRatesResponse) Reset() {
	*x = RefreshRandomRatesResponse{}
	mi := &file_fx_v1_fx_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRandomRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRandomRatesResponse) ProtoMessage() {}

func (x *RefreshRandomRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fx_v1_fx_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRandomRatesResponse.ProtoReflect.Descriptor instead.
func (*RefreshRandomRatesResponse) Descriptor() ([]byte, []int) {
	return file_fx_v1_fx_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshRandomRatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshRandomRatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshRandomRatesResponse) GetPushed() []*Rate {
	if x != nil {
		return x.Pushed
	}
	return nil
}

var File_fx_v1_fx_admin_proto protoreflect.FileDescriptor

const file_fx_v1_fx_admin_proto_rawDesc = "" +
	"\n" +
	"\x14fx/v1/fx_admin.proto\x12\x05fx.v1\x1a\x0efx/v1/fx.proto\"\x1b\n" +
	"\x19RefreshRandomRatesRequest\"u\n" +
	"\x1aRefreshRandomRatesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x06pushed\x18\x03 \x03(\v2\v.fx.v1.RateR\x06pushed2k\n" +
	"\x0eFxAdminService\x12Y\n" +
	"\x12RefreshRandomRates\x12 .fx.v1.RefreshRandomRatesRequest\x1a!.fx.v1.RefreshRandomRatesResponseB=Z;github.com/example/payment-gateway-poc/proto/gen/fx/v1;fxv1b\x06proto3"

var (
	file_fx_v1_fx_admin_proto_rawDescOnce sync.Once
	file_fx_v1_fx_admin_proto_rawDescData []byte
)

func file_fx_v1_fx_admin_proto_rawDescGZIP() []byte {
	file_fx_v1_fx_admin_proto_rawDescOnce.Do(func() {
		file_fx_v1_fx_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fx_v1_fx_admin_proto_rawDesc), len(file_fx_v1_fx_admin_proto_rawDesc)))
	})
	return file_fx_v1_fx_admin_proto_rawDescData
}

var file_fx_v1_fx_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fx_v1_fx_admin_proto_goTypes = []any{
	(*RefreshRandomRatesRequest)(nil),  // 0: fx.v1.RefreshRandomRatesRequest
	(*RefreshRandomRatesResponse)(nil), // 1: fx.v1.RefreshRandomRatesResponse
	(*Rate)(nil),                       // 2: fx.v1.Rate
}
var file_fx_v1_fx_admin_proto_depIdxs = []int32{
	2, // 0: fx.v1.RefreshRandomRatesResponse.pushed:type_name -> fx.v1.Rate
	0, // 1: fx.v1.FxAdminService.RefreshRandomRates:input_type -> fx.v1.RefreshRandomRatesRequest
	1, // 2: fx.v1.FxAdminService.RefreshRandomRates:output_type -> fx.v1.RefreshRandomRatesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fx_v1_fx_admin_proto_init() }
func file_fx_v1_fx_admin_proto_init() {
	if File_fx_v1_fx_admin_proto != nil {
		return
	}
	file_fx_v1_fx_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fx_v1_fx_admin_proto_rawDesc), len(file_fx_v1_fx_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fx_v1_fx_admin_proto_goTypes,
		DependencyIndexes: file_fx_v1_fx_admin_proto_depIdxs,
		MessageInfos:      file_fx_v1_fx_admin_proto_msgTypes,
	}.Build()
	File_fx_v1_fx_admin_proto = out.File
	file_fx_v1_fx_admin_proto_goTypes = nil
	file_fx_v1_fx_admin_proto_depIdxs = nil
}
