# payment-gateway-poc/deployments/compose/docker-compose.dev.yaml
# deployments/compose/docker-compose.dev.yaml
services:
  api-gateway:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        SERVICE: services/api-gateway
    environment:
      - HTTP_ADDR=:8080
    ports: ["8080:8080"]
    depends_on: [payments, fx, wallet, risk, prometheus, grafana]
    # opsional: hot-reload static
    volumes:
      - ../../services/api-gateway/static:/app/static:ro

  payments:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        SERVICE: services/payments
    environment: [HTTP_ADDR=:8081]
    ports: ["8081:8081"]

  fx:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        SERVICE: services/fx
    environment: [HTTP_ADDR=:8082]
    ports: ["8082:8082"]

  wallet:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        SERVICE: services/wallet
    environment: [HTTP_ADDR=:8083]
    ports: ["8083:8083"]

  risk:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
      args:
        SERVICE: services/risk
    environment: [HTTP_ADDR=:8084]
    ports: ["8084:8084"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ../../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
    # mount dashboard JSON sebagai file di dalam folder dashboards
       - ../../grafana/grafana_payment_gateway_dashboard.json:/var/lib/grafana/dashboards/payment.json:ro
    # mount seluruh provisioning directory (ini yang penting)
       - ../../grafana/provisioning:/etc/grafana/provisioning:ro
    ports: ["3000:3000"]
